# https://pre-commit.com#new-hooks
- id: format-ipy-cells
  name: Format iPython Cells
  description: Format Cells in Interactive Python Notebooks.
  entry: format-ipy-cells
  language: python
  types: [python]
  stages: [commit, push, manual]
