ci:
  autoupdate_schedule: quarterly
  skip: [ty]

default_install_hook_types: [pre-commit, commit-msg]

exclude: tests/fixtures/raw_nb.py

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        args: [--check-filenames]

  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
        types: [text]
        args: []

  - repo: https://github.com/lycheeverse/lychee
    rev: v0.15.1
    hooks:
      - id: lychee
        args: []

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check .
        language: python
