# Install these hooks with `pre-commit install`.
# Update with `pre-commit autoupdate`.
# Setup CI and readme badge at https://pre-commit.ci.
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

exclude: tests/fixtures/raw_nb.py
