name: Tests

on:
  push:
    branches: [main]
    paths: ['**.py'] # only run workflow when source files changed
  pull_request:
    branches: [main]
    paths: ['**.py']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install this hook
        run: |
          pip install .

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest --durations 0
