name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    uses: janosh/workflows/.github/workflows/pytest.yml@main
    with:
      os: ${{ matrix.os }}
      install-cmd: pip install .[test]
