name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          cache-dependency-path: setup.cfg

      - name: Install format-ipy-cells and test deps
        run: pip install .[test]

      - name: Run tests
        id: tests
        run: pytest --cov .

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'release' && needs.tests.result == 'success'
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build and upload dist
        run: |
          pip install build twine
          python -m build
          twine check dist/* --strict
          twine upload --skip-existing --repository-url https://upload.pypi.org/legacy dist/*.tar.gz
        env:
          TWINE_USERNAME: janosh
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
